---
- name: install debian dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - libc6-dev
    # This should be `else omit`, but that doesn't quite work, so duplicate gcc
    - "{{ 'libc6-dev-i386' if redis_make_32bit|bool else 'gcc' }}"
  when: ansible_os_family == "Debian"
